name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.26.x'
          check-latest: true

      - name: Run tests
        run: go test -v -race ./...

      - name: Build amd64
        run: go build ./...

      - name: Build arm64
        run: go build ./...
        env:
          GOARCH: arm64

      - name: Build 386
        run: go build ./...
        env:
          GOARCH: '386'

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          make_latest: true
